version: "3.3"
services:

  laravel10_post_phpfpm:
    build:
      args:
        user: tum
        uid: 1000
      context: .
      dockerfile: ./Dockerfile
    container_name: laravel10_post_phpfpm
    links:
      - laravel10_post_mariadb
      - laravel10_post_redis
    volumes:
      - ./docker/httpd/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - laravel10_post_network

  laravel10_post_mariadb:
    image: "mariadb:10.4.27"
    container_name: laravel10_post_mariadb
    restart: always
    ports:
      - 3501:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "DB_ROOT_PASSWORD"
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Bangkok
    networks:
      - laravel10_post_network

  laravel10_post_adminer:
    image: adminer:4.8.1
    container_name: laravel10_post_adminer
    environment:
    - ADMINER_DEFAULT_SERVER=laravel10_post_mariadb
    - ADMINER_DEFAULT_DB_DRIVER=mysql
    ports:
      - 7501:8080
    networks:
      - laravel10_post_network
  
  nginx:
    image: nginx:alpine
    container_name: laravel10_post_web
    restart: unless-stopped
    expose:
      - "8002"
    ports:
      - "8501:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - laravel10_post_network

  laravel10_post_redis:
    image: 'redis:7.0.12-alpine'
    restart: always
    container_name: laravel10_post_redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - laravel10_post_network

networks:
  laravel10_post_network:
    driver: bridge